import { GoogleGenAI, GenerateContentResponse, Chat } from "@google/genai";
import { ChatMessage } from "../types";

// Initialize Gemini Client
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Converts an image base64 string to JPEG format.
 * Essential for handling unsupported types like AVIF which browsers might upload by default.
 */
const convertToJpeg = (src: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous'; 
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      if (!ctx) {
        reject(new Error("Failed to create canvas context"));
        return;
      }
      // Fill white background for transparency
      ctx.fillStyle = '#FFFFFF';
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.drawImage(img, 0, 0);
      resolve(canvas.toDataURL('image/jpeg', 0.9));
    };
    img.onerror = () => reject(new Error("Failed to load image for conversion"));
    img.src = src;
  });
};

/**
 * Ensures the image is in a supported format (JPEG/PNG/WEBP/HEIC/HEIF).
 * Specifically converts AVIF to JPEG as Gemini API often rejects AVIF.
 */
const ensureSupportedImage = async (base64Image: string): Promise<{ mimeType: string, data: string }> => {
  let processImage = base64Image;

  // Check for AVIF or plain 'image/avif' in mime type
  if (processImage.includes('image/avif')) {
    try {
      processImage = await convertToJpeg(processImage);
    } catch (e) {
      console.warn("Image conversion failed, attempting to send original.", e);
    }
  }

  const matches = processImage.match(/^data:(.+?);base64,(.+)$/);
  if (!matches || matches.length !== 3) {
    throw new Error("Invalid base64 image format. Expected data URL.");
  }
  
  return {
    mimeType: matches[1],
    data: matches[2]
  };
};

/**
 * Uses Gemini 2.5 Flash Image (Nano Banana) to edit or reimagine an image.
 * This handles both "Reimagine as [Style]" and "Make the rug blue" type requests.
 */
export const generateEditedImage = async (
  base64Image: string,
  prompt: string
): Promise<string> => {
  try {
    // Robustly extract mimeType and base64 data, converting if necessary
    const { mimeType, data } = await ensureSupportedImage(base64Image);

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: mimeType,
              data: data,
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    // Extract the image from the response
    // The model might return text + image or just image. We iterate parts.
    const parts = response.candidates?.[0]?.content?.parts;
    if (parts) {
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/jpeg;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Gemini Image Generation Error:", error);
    throw error;
  }
};

/**
 * Uses Gemini 3 Pro Preview for the chat interface.
 * Includes Google Search grounding for shoppable links.
 */
export const sendChatMessage = async (
  history: ChatMessage[],
  newMessage: string,
  currentImageContext?: string
): Promise<{ text: string; sources: Array<{ title: string; uri: string }> }> => {
  try {
    const chat: Chat = ai.chats.create({
      model: 'gemini-3-pro-preview',
      config: {
        systemInstruction: `You are an expert Interior Design Consultant. 
        Help the user refine their room design, suggest matching colors, furniture, and layouts.
        If the user asks where to buy items, provide specific recommendations using the Search tool.
        Keep responses concise, helpful, and encouraging.`,
        tools: [{ googleSearch: {} }],
      },
    });

    // Prepare history for context if needed, though for simplicity we are sending a fresh message
    // In a real app, we would hydrate chat.history. 
    // Here we just append the user's message.
    
    const parts: any[] = [{ text: newMessage }];
    
    if (currentImageContext) {
        // Correctly handle context image mime type as well
        try {
            const { mimeType, data } = await ensureSupportedImage(currentImageContext);
            parts.push({
                inlineData: {
                    mimeType: mimeType,
                    data: data
                }
            });
            parts.push({ text: "Use this image of my room as context." });
        } catch (e) {
            console.error("Context image processing failed", e);
            // Fallback: don't include the image if it fails to process
        }
    }

    const result = await chat.sendMessage({
      content: {
          role: 'user',
          parts: parts
      }
    });

    const responseText = result.text;
    
    // Extract grounding chunks for sources
    const sources: Array<{ title: string; uri: string }> = [];
    const groundingChunks = result.candidates?.[0]?.groundingMetadata?.groundingChunks;
    
    if (groundingChunks) {
      groundingChunks.forEach((chunk: any) => {
        if (chunk.web) {
          sources.push({
            title: chunk.web.title || "Source",
            uri: chunk.web.uri,
          });
        }
      });
    }

    return { text: responseText || "I couldn't generate a response.", sources };
  } catch (error) {
    console.error("Gemini Chat Error:", error);
    return { text: "Sorry, I encountered an error while processing your request.", sources: [] };
  }
};